version: '3.8'

services:
  db:
    image: postgres:14  # Specify the version you want to use
    container_name: postgresql_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: komita
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: selim
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Optional: Persistent data storage

  testapp_con:
    build: .
    container_name: my_testapp_con  # Renamed container
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/komita
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: selim
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:  # Define the volume for PostgreSQL data
