-- -- User_table
-- INSERT INTO public.user_table (email, firstname, lastname, password, role, status) 
-- VALUES 
-- ('ketata.15.selim@gmail.com', 'Selim', 'Ketata', 'Selim22@', 'STANDARD_USER', true ),
-- ('ketata.152.selim@gmail.com', 'Selim', 'Ketata', 'Selim22@', 'ADMIN', true),
-- ('selim.ketata@ensi-uma.tn', 'Selim', 'Ketata', 'Selim22@', 'PROFESSIONAL', true);
